version: '3.8'

services:
  diff.api:
    image: ej21378/diff.api:latest
    restart: always
    network_mode: "host"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

  gnucash-version-control-web:
    image: ej21378/gnucash-version-control-web:latest
    restart: always
    network_mode: "host"
    environment:
      ApiSettings:BaseUrl: "http://localhost:5000"

  nginx:
    image: nginx:latest
    restart: always
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/etc/secrets:ro
    depends_on:
      - gnucash-version-control-web
      - diff.api